/**
 * Manages `wiki/index.md` — a generated catalog of every wiki page, grouped
 * by category, with link counts and last-updated dates. The file is
 * overwritten in full on every update; hand-edits outside the managed
 * sentinels are preserved at the bottom.
 */
import { join } from "node:path";
import { atomicWrite, readTextOrNullAsync } from "../utils/fs.js";
import type { WikiCategory, WikiPage } from "../utils/types.js";
import type { WikiStore } from "./store.js";
import { CATEGORY_DIRS } from "./store.js";

const SENTINEL_START = "<!-- wotw:index:start -->";
const SENTINEL_END = "<!-- wotw:index:end -->";

const CATEGORY_ORDER: WikiCategory[] = [
  "concept",
  "entity",
  "source",
  "comparison",
  "synthesis",
  "query",
];

const CATEGORY_LABELS: Record<WikiCategory, string> = {
  concept: "Concepts",
  entity: "Entities",
  source: "Sources",
  comparison: "Comparisons",
  synthesis: "Syntheses",
  query: "Queries",
};

export interface IndexEntry {
  category: WikiCategory;
  title: string;
  slug: string;
  relativePath: string;
  updated: string;
  confidence: string;
  linkCount: number;
}

export class IndexManager {
  private readonly store: WikiStore;
  private readonly indexPath: string;

  constructor(store: WikiStore) {
    this.store = store;
    this.indexPath = join(store.wikiRoot, "wiki", "index.md");
  }

  /**
   * Rebuild the index from a list of parsed pages. Preserves any content
   * outside the managed sentinels.
   */
  async rebuild(pages: WikiPage[]): Promise<void> {
    const entries = pages.map((p) => toEntry(this.store, p));
    const generated = renderManagedBlock(entries);

    const existing = (await readTextOrNullAsync(this.indexPath)) ?? defaultIndexShell();
    const next = replaceManagedBlock(existing, generated);
    await atomicWrite(this.indexPath, next);
  }

  /** Read the wiki index as plain markdown, or null if missing. */
  async read(): Promise<string | null> {
    return readTextOrNullAsync(this.indexPath);
  }
}

/** Build a table row from a page. */
function toEntry(store: WikiStore, page: WikiPage): IndexEntry {
  const rel = store.relativePath(page.path).replace(/\\/g, "/");
  return {
    category: page.frontmatter.category,
    title: page.frontmatter.title,
    slug: rel,
    relativePath: rel,
    updated: page.frontmatter.updated,
    confidence: page.frontmatter.confidence,
    linkCount: page.frontmatter.related.length,
  };
}

function renderManagedBlock(entries: IndexEntry[]): string {
  const lines: string[] = [];
  lines.push(SENTINEL_START);
  lines.push("# Wiki Index");
  lines.push("");
  lines.push(`_Auto-generated by watcher-on-the-wall. Last rebuilt: ${new Date().toISOString()}_`);
  lines.push("");

  const grouped = new Map<WikiCategory, IndexEntry[]>();
  for (const cat of CATEGORY_ORDER) grouped.set(cat, []);
  for (const e of entries) {
    const bucket = grouped.get(e.category);
    if (bucket) bucket.push(e);
  }

  for (const cat of CATEGORY_ORDER) {
    const items = grouped.get(cat) ?? [];
    if (items.length === 0) continue;
    lines.push(`## ${CATEGORY_LABELS[cat]} (${items.length})`);
    lines.push("");
    lines.push("| Title | Updated | Confidence | Links |");
    lines.push("|---|---|---|---|");
    items.sort((a, b) => a.title.localeCompare(b.title));
    for (const it of items) {
      lines.push(
        `| [${escapePipes(it.title)}](${it.relativePath}) | ${it.updated} | ${it.confidence} | ${it.linkCount} |`,
      );
    }
    lines.push("");
  }

  if (entries.length === 0) {
    lines.push("_No wiki pages yet. Drop files into `raw/` to begin ingestion._");
    lines.push("");
  }

  lines.push(
    `**Totals:** ${entries.length} pages across ${CATEGORY_ORDER.filter((c) => (grouped.get(c) ?? []).length > 0).length} categories.`,
  );
  lines.push("");
  lines.push(SENTINEL_END);
  return lines.join("\n");
}

function replaceManagedBlock(existing: string, generated: string): string {
  const startIdx = existing.indexOf(SENTINEL_START);
  const endIdx = existing.indexOf(SENTINEL_END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    return `${generated}\n\n${existing.trim()}\n`;
  }
  const before = existing.slice(0, startIdx);
  const after = existing.slice(endIdx + SENTINEL_END.length);
  return `${before}${generated}${after}`;
}

function defaultIndexShell(): string {
  return [
    "# Wiki",
    "",
    "Welcome to the watcher-on-the-wall wiki. The block below is generated automatically.",
    "",
    SENTINEL_START,
    SENTINEL_END,
    "",
  ].join("\n");
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}

/** Re-export category constants for callers that render indexes themselves. */
export { CATEGORY_DIRS };
